"""empty message

Revision ID: 6697cb00d615
Revises: 7bd8ee525f17
Create Date: 2026-09-11 13:04:49.794710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6697cb00d615'
down_revision: Union[str, Sequence[str], None] = '7bd8ee525f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('login', sa.String(), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'role')
    op.drop_column('users', 'login')
    op.alter_column('staff', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
